### ISSUE TITLE
Poor test results

### ISSUE THREAD

**Issue by jh2807** [JunhwanRyu/ssd-pytorch#1]
Hello After training according to your process, after testing, countless prediction boxes appear.Just like this,
![p_2](https://user-images.githubusercontent.com/22724436/80276916-34091300-871e-11ea-8cc3-6105f345b635.jpg)

**Comment by ynrjh92** [comment]
Hello,

This is probably because the "min-score" argument has a very low reference value.

Please increase the value of the "min-score" argument as below.

`python detect_image.py --trained-model="trained-model"  --test-image="test-image" --min-score=0.2`

**Comment by jh2807** [comment]
Thank you very munch,I will try it soon!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jhryu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 晚上9:20
收件人:&nbsp;"JunhwanRyu/ssd-pytorch"<ssd-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"ツ笙歌绝丶何以笙箫默"<453896505@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JunhwanRyu/ssd-pytorch] Poor test results (#1)





 
Hello,
 
This is probably because the "min-score" has a very low reference value.
 
Please increase the value of the "min-score" argument as below.
 
python detect_image.py --trained-model="trained-model"  --test-image="test-image" --min-score=0.2

**Comment by ynrjh92** [comment]
The issue seems to have been resolved, so close the issue.
